{application,exfswatch,
             [{applications,[kernel,stdlib,elixir]},
              {description,"A file change watcher wrapper based on [fs](https://github.com/synrc/fs)"},
              {modules,['Elixir.ExFSWatch',
                        'Elixir.ExFSWatch.Backends.Fsevents',
                        'Elixir.ExFSWatch.Backends.InotifyWait',
                        'Elixir.ExFSWatch.Backends.InotifyWaitWin32',
                        'Elixir.ExFSWatch.Backends.Kqueue',
                        'Elixir.ExFSWatch.Supervisor',
                        'Elixir.ExFSWatch.Utils','Elixir.ExFSWatch.Worker']},
              {registered,[]},
              {vsn,"0.4.1"},
              {mod,{'Elixir.ExFSWatch',[]}},
              {included_applications,[logger]}]}.
